https://hackerone.com/reports/113941


This is a minor glitch in your Python Library

`client.get_notifications()` creates a `TypeError: unhashable type: 'dict'`

See details in here:
https://github.com/drandreaskrueger/coinbaseTestbed/blob/master/output/cbNotificationsBug.py.txt
There is also a full prinout of the data which causes your library to fail, so you can dbug it.

The .txt was generated by this code:
https://github.com/drandreaskrueger/coinbaseTestbed/blob/master/cb/cbNotificationsBug.py


Security relevance: Low. 

But it cost me time to find, and examine this bug.

As your official Python library did not provide me with the `get_notifications` information, I had to code an own Authentication class:
https://github.com/drandreaskrueger/coinbaseTestbed/blob/master/cb/cbAuthenticationBasics.py

It held me up while I was coding. 

Please reward my work, thanks.
Andreas
